#!/usr/bin/python3

from sys import argv

def main() -> int:
    if len(argv) < 2:
        return 84
    if len(argv) == 2 and argv[1] == "-h":
        return display_usage()
    return compute_all(argv[1:-1])

if __name__ == "__main__":
    exit(main())
