#!/usr/bin/python3

from sys import argv
from src.display_usage import display_usage
from src.compute_all import compute_all

def main() -> int:
    if len(argv) < 2:
        return 84
    if len(argv) == 2 and argv[1] == "-h":
        return display_usage()
    return compute_all(argv[1:])

if __name__ == "__main__":
    exit(main())
